### ISSUE TITLE
amogus

### ISSUE THREAD

**Issue by Lamby777** [NalinPlad/NalinPlad#1]
that's a pretty sus hash at the bottom of the readme, we should call an emergency meeting
![image](https://user-images.githubusercontent.com/35111165/201759977-0cab8afa-1a3c-46eb-ad76-c1fd9cb361b2.png)

(found you from typing hashes into google while i was bored lol)

**Comment by NalinPlad** [comment]
Yo that's crazy someone actually found it (I kinda forgot what it was for a bit lol)

**Comment by Lamby777** [comment]
fr, never underestimate the power of big brother google lol
